### ISSUE TITLE
DArk theme for website

### ISSUE THREAD

**Issue by nainardev** [heytulsiprasad/picturesque.css#6]

**Comment by heytulsiprasad** [comment]
### Awesome :tada:
I think that feature would be dope! I'll take that into my **todo** list. Do you wanna work on this?

**Comment by nainardev** [comment]
Not qualified enough. 
U could do it

**Comment by heytulsiprasad** [comment]
That's alright, I'm working on some other projects too. You can learn eventually. I'm here to help! 🙌
